-- printing full description of a table in the database

SELECT VARCHAR, INT, 256, IS_NULLABLE, COLUMN_KEY, COLUMN_DEFAULT, EXTRA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = hbtn_0c_0 AND TABLE_NAME = first_table;

